# Generated by Django 5.0.2 on 2024-03-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='availbe_time',
        ),
        migrations.AddField(
            model_name='doctor',
            name='availbe_time',
            field=models.ManyToManyField(to='doctor.availbetime'),
        ),
    ]
